export enum experienceType {
  ENTRY = 'ENTRY',
  INTERMEDIATE = 'INTERMEDIATE',
  EXPERT = 'EXPERT',
}

export enum employementType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  CONTRACT = 'CONTRACT',
  INTERNSHIP = 'INTERNSHIP',
  HOURLY = 'HOURLY',
}



export enum status{
  NOT_APPLIED="NOT_APPLIED",
  APPLIED="APPLIED",
  UNDER_REVIEW="UNDER_REVIEW",
  SELECTED="SELECTED",
  REJECTED="REJECTED",
}
